/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 15:48:29 GMT 2018
 */

package com.jfinal.template.stat;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jfinal.template.stat.ParaToken;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class ParaToken_ESTest extends ParaToken_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      StringBuilder stringBuilder1 = stringBuilder0.insert(0, "p~;%");
      ParaToken paraToken0 = new ParaToken(stringBuilder1, 3272);
      String string0 = paraToken0.value();
      assertEquals("p~;%", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      ParaToken paraToken0 = new ParaToken(stringBuilder0, 1);
      String string0 = paraToken0.value();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      ParaToken paraToken0 = new ParaToken(stringBuilder0, 3272);
      StringBuilder stringBuilder1 = paraToken0.getContent();
      assertSame(stringBuilder1, stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParaToken paraToken0 = new ParaToken((StringBuilder) null, 0);
      String string0 = paraToken0.toString();
      assertEquals("null", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StringBuilder stringBuilder0 = new StringBuilder();
      ParaToken paraToken0 = new ParaToken(stringBuilder0, (-3352));
      String string0 = paraToken0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ParaToken paraToken0 = new ParaToken((StringBuilder) null, (-20));
      paraToken0.print();
      assertEquals("null", paraToken0.toString());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ParaToken paraToken0 = new ParaToken((StringBuilder) null, (-20));
      StringBuilder stringBuilder0 = paraToken0.getContent();
      assertNull(stringBuilder0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ParaToken paraToken0 = new ParaToken((StringBuilder) null, (-20));
      // Undeclared exception!
      try { 
        paraToken0.value();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jfinal.template.stat.ParaToken", e);
      }
  }
}
