/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 18:21:36 GMT 2018
 */

package com.jfinal.plugin.auth;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jfinal.plugin.auth.ISession;
import com.jfinal.plugin.auth.SessionKit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class SessionKit_ESTest extends SessionKit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SessionKit sessionKit0 = new SessionKit();
      ISession iSession0 = sessionKit0.getSession("rx! >2$", false);
      assertNull(iSession0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SessionKit sessionKit0 = new SessionKit();
      sessionKit0.removeSession("fi.^wX<!~jH9$|s");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SessionKit sessionKit0 = new SessionKit();
      ISession iSession0 = sessionKit0.getSession("fi.^wX<!~jH9$|s");
      assertNull(iSession0);
  }
}
