/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 13:19:28 GMT 2018
 */

package com.puppycrawl.tools.checkstyle.checks.annotation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationLocationCheck;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnnotationLocationCheck_ESTest extends AnnotationLocationCheck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      DetailAST detailAST0 = new DetailAST();
      DetailAST detailAST1 = new DetailAST();
      detailAST0.addChild(detailAST1);
      detailAST0.addChild(detailAST1);
      // Undeclared exception!
      annotationLocationCheck0.visitToken(detailAST0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      // Undeclared exception!
      try { 
        annotationLocationCheck0.visitToken((DetailAST) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationLocationCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      DetailAST detailAST0 = new DetailAST();
      annotationLocationCheck0.visitToken(detailAST0);
      assertEquals(0, detailAST0.getNumberOfChildren());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      int[] intArray0 = annotationLocationCheck0.getAcceptableTokens();
      assertEquals(15, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      int[] intArray0 = annotationLocationCheck0.getRequiredTokens();
      assertEquals(0, intArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      annotationLocationCheck0.setAllowSamelineMultipleAnnotations(false);
      assertNull(annotationLocationCheck0.getId());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      int[] intArray0 = annotationLocationCheck0.getDefaultTokens();
      assertArrayEquals(new int[] {14, 15, 154, 9, 8, 10}, intArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      annotationLocationCheck0.setAllowSamelineParameterizedAnnotation(false);
      assertNull(annotationLocationCheck0.getId());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      AnnotationLocationCheck annotationLocationCheck0 = new AnnotationLocationCheck();
      annotationLocationCheck0.setAllowSamelineSingleParameterlessAnnotation(false);
      assertFalse(annotationLocationCheck0.isCommentNodesRequired());
  }
}
