/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 18:20:17 GMT 2018
 */

package com.jfinal.plugin.activerecord.generator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jfinal.plugin.activerecord.generator.TypeMapping;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class TypeMapping_ESTest extends TypeMapping_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TypeMapping typeMapping0 = new TypeMapping();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      typeMapping0.map = (Map<String, String>) hashMap0;
      hashMap0.put((String) null, "6=@FGW}GWZc~");
      String string0 = typeMapping0.getType((String) null);
      assertEquals("6=@FGW}GWZc~", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TypeMapping typeMapping0 = new TypeMapping();
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      typeMapping0.map = (Map<String, String>) hashMap0;
      hashMap0.put((String) null, "");
      String string0 = typeMapping0.getType((String) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TypeMapping typeMapping0 = new TypeMapping();
      Map<String, String> map0 = typeMapping0.map;
      typeMapping0.map = map0;
      typeMapping0.map = null;
      // Undeclared exception!
      try { 
        typeMapping0.getType("cJ*");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jfinal.plugin.activerecord.generator.TypeMapping", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TypeMapping typeMapping0 = new TypeMapping();
      String string0 = typeMapping0.getType("ZND[QSgXRZ");
      assertNull(string0);
  }
}
