/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 13:32:17 GMT 2018
 */

package com.puppycrawl.tools.checkstyle.xpath;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.api.FileText;
import com.puppycrawl.tools.checkstyle.xpath.XpathQueryGenerator;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XpathQueryGenerator_ESTest extends XpathQueryGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DetailAST detailAST0 = new DetailAST();
      XpathQueryGenerator xpathQueryGenerator0 = new XpathQueryGenerator(detailAST0, (-27), (-27), (FileText) null, (-27));
      detailAST0.addPreviousSibling(detailAST0);
      // Undeclared exception!
      xpathQueryGenerator0.generate();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DetailAST detailAST0 = new DetailAST();
      XpathQueryGenerator xpathQueryGenerator0 = new XpathQueryGenerator(detailAST0, (-27), (-27), (FileText) null, (-27));
      detailAST0.setLineNo((-27));
      // Undeclared exception!
      try { 
        xpathQueryGenerator0.generate();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.xpath.XpathQueryGenerator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DetailAST detailAST0 = new DetailAST();
      XpathQueryGenerator xpathQueryGenerator0 = new XpathQueryGenerator(detailAST0, (-87), (-87), (FileText) null, (-87));
      DetailAST detailAST1 = new DetailAST();
      detailAST0.addNextSibling(detailAST1);
      List<String> list0 = xpathQueryGenerator0.generate();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DetailAST detailAST0 = new DetailAST();
      detailAST0.setLineNo((-1781));
      XpathQueryGenerator xpathQueryGenerator0 = new XpathQueryGenerator(detailAST0, (-2635), (-1781), (FileText) null, (-1781));
      List<String> list0 = xpathQueryGenerator0.generate();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DetailAST detailAST0 = new DetailAST();
      MockFile mockFile0 = new MockFile("", "");
      LinkedList<String> linkedList0 = new LinkedList<String>();
      FileText fileText0 = new FileText(mockFile0, linkedList0);
      XpathQueryGenerator xpathQueryGenerator0 = new XpathQueryGenerator(detailAST0, Integer.MIN_VALUE, 0, fileText0, 0);
      // Undeclared exception!
      try { 
        xpathQueryGenerator0.generate();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2147483647
         //
         verifyException("com.puppycrawl.tools.checkstyle.api.FileText", e);
      }
  }
}
