/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 14:25:11 GMT 2018
 */

package com.puppycrawl.tools.checkstyle.checks.coding;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.api.SeverityLevel;
import com.puppycrawl.tools.checkstyle.checks.coding.IllegalThrowsCheck;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IllegalThrowsCheck_ESTest extends IllegalThrowsCheck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      DetailAST detailAST0 = new DetailAST();
      // Undeclared exception!
      try { 
        illegalThrowsCheck0.visitToken(detailAST0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.coding.IllegalThrowsCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        illegalThrowsCheck0.setIllegalClassNames(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.utils.CheckUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      // Undeclared exception!
      try { 
        illegalThrowsCheck0.setIgnoredMethodNames((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      int[] intArray0 = illegalThrowsCheck0.getRequiredTokens();
      assertArrayEquals(new int[] {81}, intArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      String[] stringArray0 = new String[0];
      illegalThrowsCheck0.setIllegalClassNames(stringArray0);
      assertEquals(SeverityLevel.ERROR, illegalThrowsCheck0.getSeverityLevel());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      String[] stringArray0 = new String[0];
      illegalThrowsCheck0.setIgnoredMethodNames(stringArray0);
      assertEquals(SeverityLevel.ERROR, illegalThrowsCheck0.getSeverityLevel());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      int[] intArray0 = illegalThrowsCheck0.getDefaultTokens();
      assertArrayEquals(new int[] {81}, intArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      illegalThrowsCheck0.setIgnoreOverriddenMethods(true);
      assertFalse(illegalThrowsCheck0.isCommentNodesRequired());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      IllegalThrowsCheck illegalThrowsCheck0 = new IllegalThrowsCheck();
      int[] intArray0 = illegalThrowsCheck0.getAcceptableTokens();
      assertArrayEquals(new int[] {81}, intArray0);
  }
}
