/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 14:39:18 GMT 2018
 */

package com.puppycrawl.tools.checkstyle.checks.imports;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.api.SeverityLevel;
import com.puppycrawl.tools.checkstyle.checks.imports.AvoidStaticImportCheck;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AvoidStaticImportCheck_ESTest extends AvoidStaticImportCheck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AvoidStaticImportCheck avoidStaticImportCheck0 = new AvoidStaticImportCheck();
      DetailAST detailAST0 = new DetailAST();
      // Undeclared exception!
      try { 
        avoidStaticImportCheck0.visitToken(detailAST0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.imports.AvoidStaticImportCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AvoidStaticImportCheck avoidStaticImportCheck0 = new AvoidStaticImportCheck();
      // Undeclared exception!
      try { 
        avoidStaticImportCheck0.setExcludes((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.imports.AvoidStaticImportCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AvoidStaticImportCheck avoidStaticImportCheck0 = new AvoidStaticImportCheck();
      int[] intArray0 = avoidStaticImportCheck0.getRequiredTokens();
      assertArrayEquals(new int[] {152}, intArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AvoidStaticImportCheck avoidStaticImportCheck0 = new AvoidStaticImportCheck();
      int[] intArray0 = avoidStaticImportCheck0.getAcceptableTokens();
      assertArrayEquals(new int[] {152}, intArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AvoidStaticImportCheck avoidStaticImportCheck0 = new AvoidStaticImportCheck();
      int[] intArray0 = avoidStaticImportCheck0.getDefaultTokens();
      assertArrayEquals(new int[] {152}, intArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AvoidStaticImportCheck avoidStaticImportCheck0 = new AvoidStaticImportCheck();
      String[] stringArray0 = new String[14];
      avoidStaticImportCheck0.setExcludes(stringArray0);
      assertEquals(SeverityLevel.ERROR, avoidStaticImportCheck0.getSeverityLevel());
  }
}
