/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Apr 18 13:10:46 GMT 2018
 */

package com.puppycrawl.tools.checkstyle;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class JavadocDetailNodeParser_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\GUDEK-~1\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Gudek-Home\\Documents\\TU\\STRE\\STRE-FinalProject\\checkstyle"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\Gudek-Home"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "Gudek-Home"); 
    java.lang.System.setProperty("user.timezone", "Europe/Berlin"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(JavadocDetailNodeParser_ESTest_scaffolding.class.getClassLoader() ,
      "antlr.collections.AST",
      "org.antlr.v4.runtime.ANTLRErrorStrategy",
      "com.google.common.base.CharMatcher$ForPredicate",
      "org.antlr.v4.runtime.atn.ArrayPredictionContext",
      "org.antlr.v4.runtime.tree.pattern.RuleTagToken",
      "org.antlr.v4.runtime.tree.pattern.TextChunk",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$SourceTagContext",
      "org.antlr.v4.runtime.tree.pattern.Chunk",
      "org.antlr.v4.runtime.atn.LoopEndState",
      "org.antlr.v4.runtime.tree.pattern.ParseTreeMatch",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$ParseErrorMessage",
      "org.antlr.v4.runtime.misc.IntSet",
      "com.google.common.base.CharMatcher$JavaLetterOrDigit",
      "org.antlr.v4.runtime.CommonToken",
      "org.antlr.v4.runtime.Recognizer",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$EmbedTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser",
      "com.google.common.base.Converter$IdentityConverter",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DtTagStartContext",
      "org.antlr.v4.runtime.atn.PredicateTransition",
      "com.google.common.base.Predicate",
      "org.antlr.v4.runtime.atn.EmptyPredictionContext",
      "antlr.ParseTreeToken",
      "com.google.common.base.CharMatcher$Invisible",
      "antlr.CommonASTWithHiddenTokens",
      "com.google.common.base.CharMatcher$None",
      "com.puppycrawl.tools.checkstyle.api.DetailAST",
      "org.antlr.v4.runtime.atn.TokensStartState",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ParagraphContext",
      "org.antlr.v4.runtime.atn.DecisionState",
      "org.antlr.v4.runtime.atn.ATNConfigSet$ConfigEqualityComparator",
      "org.antlr.v4.runtime.atn.BlockEndState",
      "antlr.Token",
      "org.antlr.v4.runtime.atn.EpsilonTransition",
      "org.antlr.v4.runtime.atn.ActionTransition",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DtContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$FrameTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TfootContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlElementStartContext",
      "org.antlr.v4.runtime.FailedPredicateException",
      "org.antlr.v4.runtime.atn.ParserATNSimulator",
      "org.antlr.v4.runtime.dfa.DFASerializer",
      "org.antlr.v4.runtime.atn.ProfilingATNSimulator",
      "org.antlr.v4.runtime.atn.AtomTransition",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ColgroupTagEndContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DdContext",
      "com.google.common.base.CharMatcher",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TrTagEndContext",
      "org.antlr.v4.runtime.atn.PredictionMode",
      "org.antlr.v4.runtime.TokenSource",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ThTagEndContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$SingletonElementContext",
      "org.antlr.v4.runtime.atn.ATNDeserializationOptions",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ColTagContext",
      "org.antlr.v4.runtime.RecognitionException",
      "org.antlr.v4.runtime.Parser",
      "com.puppycrawl.tools.checkstyle.api.JavadocTokenTypes",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$AreaTagContext",
      "org.antlr.v4.runtime.tree.ParseTreeListener",
      "org.antlr.v4.runtime.atn.RangeTransition",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$JavadocParserErrorStrategy",
      "org.antlr.v4.runtime.VocabularyImpl",
      "com.google.common.base.Preconditions",
      "antlr.BaseAST",
      "com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTags",
      "com.google.common.base.CharMatcher$1",
      "org.antlr.v4.runtime.ANTLRErrorListener",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DescriptionContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$EmptyTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$OptionContext",
      "com.google.common.base.CharMatcher$FastMatcher",
      "org.antlr.v4.runtime.atn.ATNConfigSet$AbstractConfigHashSet",
      "com.google.common.base.CharMatcher$JavaIsoControl",
      "org.antlr.v4.runtime.misc.Interval",
      "com.google.common.base.Converter$ConverterComposition",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TfootTagStartContext",
      "org.antlr.v4.runtime.TokenStream",
      "org.antlr.v4.runtime.atn.StarLoopbackState",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlElementEndContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TdTagStartContext",
      "org.antlr.v4.runtime.misc.EqualityComparator",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$PTagEndContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TheadTagStartContext",
      "org.antlr.v4.runtime.misc.MurmurHash",
      "com.puppycrawl.tools.checkstyle.utils.JavadocUtils$JavadocTagType",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TheadTagEndContext",
      "com.google.common.base.CharMatcher$BitSetMatcher",
      "com.google.common.base.CharMatcher$JavaUpperCase",
      "org.antlr.v4.runtime.atn.SemanticContext$Predicate",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TbodyTagEndContext",
      "org.antlr.v4.runtime.TokenFactory",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$WbrTagContext",
      "org.antlr.v4.runtime.misc.Array2DHashSet",
      "com.google.common.base.CharMatcher$NamedFastMatcher",
      "org.antlr.v4.runtime.tree.Tree",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ThTagStartContext",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$1",
      "org.antlr.v4.runtime.Vocabulary",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$InputTagContext",
      "com.puppycrawl.tools.checkstyle.utils.TokenUtils",
      "antlr.ASTNULLType",
      "com.google.common.base.Converter$ReverseConverter",
      "org.antlr.v4.runtime.atn.PredictionContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlTagEndContext",
      "com.google.common.base.CharMatcher$Is",
      "org.antlr.v4.runtime.WritableToken",
      "com.google.common.base.CharMatcher$SingleWidth",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ThContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TbodyContext",
      "org.antlr.v4.runtime.atn.PlusLoopbackState",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$LiTagStartContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$JavadocTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$OptionTagEndContext",
      "org.antlr.v4.runtime.atn.PredictionContextCache",
      "com.puppycrawl.tools.checkstyle.utils.CommonUtils",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TrackTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TextContext",
      "org.antlr.v4.runtime.atn.SemanticContext$OR",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$BasefontTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlElementContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TrTagStartContext",
      "antlr.CommonAST",
      "org.antlr.v4.runtime.tree.pattern.ParseTreePatternMatcher$StartRuleDoesNotConsumeFullPattern",
      "org.antlr.v4.runtime.atn.Transition",
      "org.antlr.v4.runtime.atn.ATNDeserializer",
      "com.puppycrawl.tools.checkstyle.utils.JavadocUtils",
      "com.google.common.base.CharMatcher$Negated",
      "com.puppycrawl.tools.checkstyle.api.DetailNode",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$MetaTagContext",
      "com.google.common.base.CharMatcher$Ascii",
      "org.antlr.v4.runtime.LexerNoViableAltException",
      "org.antlr.v4.runtime.atn.ATNDeserializer$UnicodeDeserializer",
      "org.antlr.v4.runtime.atn.SetTransition",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "org.antlr.v4.runtime.tree.pattern.ParseTreePatternMatcher",
      "org.antlr.v4.runtime.atn.SemanticContext$Operator",
      "org.antlr.v4.runtime.atn.ATN",
      "org.antlr.v4.runtime.atn.ATNConfigSet$ConfigHashSet",
      "org.antlr.v4.runtime.dfa.LexerDFASerializer",
      "com.google.common.base.CharMatcher$Digit",
      "antlr.collections.ASTEnumeration",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TheadContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HrTagContext",
      "org.antlr.v4.runtime.atn.BlockStartState",
      "org.antlr.v4.runtime.tree.SyntaxTree",
      "org.antlr.v4.runtime.tree.RuleNode",
      "com.puppycrawl.tools.checkstyle.api.TextBlock",
      "org.antlr.v4.runtime.atn.NotSetTransition",
      "com.google.common.base.CharMatcher$Whitespace",
      "org.antlr.v4.runtime.Token",
      "org.antlr.v4.runtime.atn.ATNState",
      "org.antlr.v4.runtime.misc.AbstractEqualityComparator",
      "org.antlr.v4.runtime.atn.DecisionInfo",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlTagStartContext",
      "com.google.common.base.CharMatcher$JavaDigit",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ParamTagContext",
      "org.antlr.v4.runtime.atn.PlusBlockStartState",
      "org.antlr.v4.runtime.IntStream",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ColgroupTagStartContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TdTagEndContext",
      "org.antlr.v4.runtime.misc.Pair",
      "org.antlr.v4.runtime.atn.AbstractPredicateTransition",
      "antlr.collections.impl.Vector",
      "com.google.common.base.CharMatcher$InRange",
      "com.google.common.base.CharMatcher$IsNot",
      "com.google.common.base.CharMatcher$JavaLetter",
      "com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocNodeImpl",
      "com.google.common.base.CharMatcher$NegatedFastMatcher",
      "org.antlr.v4.runtime.misc.IntegerList",
      "org.antlr.v4.runtime.atn.ATNConfig",
      "org.antlr.v4.runtime.atn.ATNDeserializer$UnicodeDeserializingMode",
      "antlr.ParseTree",
      "org.antlr.v4.runtime.misc.MultiMap",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$BaseTagContext",
      "org.antlr.v4.runtime.tree.TerminalNode",
      "org.antlr.v4.runtime.atn.RuleStartState",
      "antlr.ParseTreeRule",
      "org.antlr.v4.runtime.atn.Transition$1",
      "org.antlr.v4.runtime.atn.ATNSimulator",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$JavadocInlineTagContext",
      "com.google.common.base.CharMatcher$IsEither",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DdTagStartContext",
      "org.antlr.v4.runtime.ParserRuleContext",
      "org.antlr.v4.runtime.tree.ErrorNode",
      "org.antlr.v4.runtime.dfa.DFAState",
      "com.google.common.base.CharMatcher$Any",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$BrTagContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$LiContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$PTagStartContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$OptionTagStartContext",
      "org.antlr.v4.runtime.RuleContext",
      "org.antlr.v4.runtime.atn.LexerActionType",
      "org.antlr.v4.runtime.CharStream",
      "org.antlr.v4.runtime.DefaultErrorStrategy",
      "org.antlr.v4.runtime.tree.ParseTree",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$SingletonTagNameContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$BodyTagStartContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DtTagEndContext",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$ParseStatus",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$KeygenTagContext",
      "org.antlr.v4.runtime.tree.pattern.ParseTreePatternMatcher$CannotInvokeStartRule",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TbodyTagStartContext",
      "com.google.common.base.CaseFormat$1",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ParametersContext",
      "com.google.common.base.CaseFormat$2",
      "com.google.common.base.CaseFormat$3",
      "com.google.common.base.CaseFormat$4",
      "com.google.common.base.CaseFormat$5",
      "com.google.common.base.CharMatcher$And",
      "org.antlr.v4.runtime.BailErrorStrategy",
      "org.antlr.v4.runtime.atn.LexerAction",
      "com.google.common.base.CharMatcher$AnyOf",
      "org.antlr.v4.runtime.dfa.DFAState$PredPrediction",
      "org.antlr.v4.runtime.atn.WildcardTransition",
      "org.antlr.v4.runtime.dfa.DFA",
      "org.antlr.v4.runtime.atn.RuleTransition",
      "antlr.collections.impl.ASTEnumerator",
      "org.antlr.v4.runtime.tree.pattern.TagChunk",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlTagContext",
      "org.antlr.v4.runtime.BaseErrorListener",
      "org.antlr.v4.runtime.tree.ParseTreeVisitor",
      "org.antlr.v4.runtime.Lexer",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TfootTagEndContext",
      "org.antlr.v4.runtime.atn.PrecedencePredicateTransition",
      "com.google.common.base.CharMatcher$RangesMatcher",
      "com.google.common.base.Converter",
      "org.antlr.v4.runtime.atn.SingletonPredictionContext",
      "com.google.common.base.Function",
      "org.antlr.v4.runtime.atn.StarBlockStartState",
      "com.google.common.base.CharMatcher$BreakingWhitespace",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$WrongSingletonTagContext",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$DescriptiveErrorListener",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$BodyContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlCommentContext",
      "com.puppycrawl.tools.checkstyle.api.TokenTypes",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HeadTagStartContext",
      "antlr.CommonToken",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TdContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HtmlContext",
      "org.antlr.v4.runtime.atn.BasicBlockStartState",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$TrContext",
      "org.antlr.v4.runtime.misc.DoubleKeyMap",
      "com.google.common.base.CharMatcher$JavaLowerCase",
      "com.puppycrawl.tools.checkstyle.api.CheckstyleException",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$LinkTagContext",
      "org.antlr.v4.runtime.misc.IntervalSet",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$DdTagEndContext",
      "org.antlr.v4.runtime.misc.ParseCancellationException",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ImgTagContext",
      "org.antlr.v4.runtime.atn.BasicState",
      "org.antlr.v4.runtime.NoViableAltException",
      "org.antlr.v4.runtime.RuntimeMetaData",
      "org.antlr.v4.runtime.atn.SemanticContext$AND",
      "org.antlr.v4.runtime.atn.ATNConfigSet",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HeadContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$IsindexTagContext",
      "org.antlr.v4.runtime.atn.ParseInfo",
      "org.antlr.v4.runtime.atn.SemanticContext$PrecedencePredicate",
      "org.antlr.v4.runtime.misc.ObjectEqualityComparator",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$LiTagEndContext",
      "antlr.collections.impl.VectorEnumerator",
      "org.antlr.v4.runtime.InputMismatchException",
      "antlr.CommonHiddenStreamToken",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$BodyTagEndContext",
      "com.google.common.base.CaseFormat",
      "org.antlr.v4.runtime.atn.SemanticContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ReferenceContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$AttributeContext",
      "com.google.common.base.CharMatcher$Or",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$HeadTagEndContext",
      "org.antlr.v4.runtime.tree.pattern.ParseTreePattern",
      "org.antlr.v4.runtime.atn.RuleStopState",
      "com.google.common.base.CaseFormat$StringConverter",
      "org.antlr.v4.runtime.atn.StarLoopEntryState",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$JavadocContext",
      "com.puppycrawl.tools.checkstyle.grammars.javadoc.JavadocParser$ColgroupContext"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(JavadocDetailNodeParser_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser",
      "org.antlr.v4.runtime.BaseErrorListener",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$DescriptiveErrorListener",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$ParseStatus",
      "org.antlr.v4.runtime.DefaultErrorStrategy",
      "org.antlr.v4.runtime.BailErrorStrategy",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$JavadocParserErrorStrategy",
      "com.puppycrawl.tools.checkstyle.JavadocDetailNodeParser$ParseErrorMessage",
      "com.puppycrawl.tools.checkstyle.api.TokenTypes",
      "com.puppycrawl.tools.checkstyle.utils.CommonUtils",
      "com.puppycrawl.tools.checkstyle.utils.TokenUtils",
      "com.puppycrawl.tools.checkstyle.api.JavadocTokenTypes",
      "com.puppycrawl.tools.checkstyle.utils.JavadocUtils",
      "com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocNodeImpl",
      "com.google.common.base.CharMatcher$BreakingWhitespace",
      "com.google.common.base.Preconditions",
      "com.google.common.base.CharMatcher$Ascii",
      "com.google.common.base.CharMatcher$RangesMatcher",
      "com.google.common.base.CharMatcher$Digit",
      "com.google.common.base.CharMatcher$JavaDigit",
      "com.google.common.base.CharMatcher$JavaLetter",
      "com.google.common.base.CharMatcher$JavaLetterOrDigit",
      "com.google.common.base.CharMatcher$JavaUpperCase",
      "com.google.common.base.CharMatcher$JavaLowerCase",
      "com.google.common.base.CharMatcher$JavaIsoControl",
      "com.google.common.base.CharMatcher$Invisible",
      "com.google.common.base.CharMatcher$SingleWidth",
      "com.google.common.base.CharMatcher$Any",
      "com.google.common.base.CharMatcher$None",
      "com.google.common.base.CharMatcher",
      "com.google.common.base.CharMatcher$FastMatcher",
      "com.google.common.base.CharMatcher$NamedFastMatcher",
      "com.google.common.base.CharMatcher$Whitespace",
      "com.google.common.base.CharMatcher$Is",
      "com.google.common.base.CharMatcher$InRange",
      "com.google.common.base.CaseFormat",
      "antlr.BaseAST",
      "antlr.CommonAST",
      "antlr.CommonASTWithHiddenTokens",
      "com.puppycrawl.tools.checkstyle.api.DetailAST",
      "antlr.collections.impl.Vector",
      "antlr.ParseTree",
      "antlr.ParseTreeRule",
      "antlr.collections.impl.ASTEnumerator",
      "antlr.collections.impl.VectorEnumerator",
      "antlr.ASTNULLType",
      "org.antlr.v4.runtime.misc.Pair",
      "org.antlr.v4.runtime.CommonToken",
      "antlr.Token",
      "antlr.ParseTreeToken"
    );
  }
}
