/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Apr 18 15:15:32 GMT 2018
 */

package com.jfinal.render;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class Render_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.jfinal.render.Render"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/agudek/Documents/STRE/final_project/jfinal"); 
    java.lang.System.setProperty("user.home", "/home/agudek"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "agudek"); 
    java.lang.System.setProperty("user.timezone", "Europe/Amsterdam"); 
    java.lang.System.setProperty("log4j.configuration", "SUT.log4j.properties"); 
    java.lang.System.setProperty("org.evosuite.shaded.org.dom4j.dom.DOMDocumentFactory.singleton.strategy", "org.evosuite.shaded.org.dom4j.util.SimpleSingleton"); 
    java.lang.System.setProperty("strategy", "EvoSuite"); 
    java.lang.System.setProperty("sun.java.launcher", "SUN_STANDARD"); 
    java.lang.System.setProperty("sun.management.compiler", "HotSpot 64-Bit Tiered Compilers"); 
    java.lang.System.setProperty("sun.boot.class.path", "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"); 
    java.lang.System.setProperty("show_progress", "false"); 
    java.lang.System.setProperty("extra_timeout", "6"); 
    java.lang.System.setProperty("sun.desktop", "gnome"); 
    java.lang.System.setProperty("process_communication_port", "5311"); 
    java.lang.System.setProperty("initialization_timeout", "6"); 
    java.lang.System.setProperty("org.evosuite.shaded.org.dom4j.factory", "org.evosuite.shaded.org.dom4j.DocumentFactory"); 
    java.lang.System.setProperty("assertion_timeout", "6"); 
    java.lang.System.setProperty("junit_tests", "true"); 
    java.lang.System.setProperty("analysis_criteria", ""); 
    java.lang.System.setProperty("sun.boot.library.path", "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"); 
    java.lang.System.setProperty("enable_asserts_for_evosuite", "false"); 
    java.lang.System.setProperty("sun.arch.data.model", "64"); 
    java.lang.System.setProperty("sun.cpu.isalist", ""); 
    java.lang.System.setProperty("sun.jnu.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.encoding.pkg", "sun.io"); 
    java.lang.System.setProperty("configuration_id", "default"); 
    java.lang.System.setProperty("PROJECT_PREFIX", ""); 
    java.lang.System.setProperty("ctg_time_per_class", "2"); 
    java.lang.System.setProperty("write_pool", "/home/agudek/Documents/STRE/final_project/jfinal/.evosuite/tmp_2018_04_18_12_08_53/pools/com.jfinal.render.Render.pool"); 
    java.lang.System.setProperty("save_all_data", "false"); 
    java.lang.System.setProperty("logback.configurationFile", "logback-ctg.xml"); 
    java.lang.System.setProperty("junit_check_timeout", "6"); 
    java.lang.System.setProperty("replace_calls", "true"); 
    java.lang.System.setProperty("coverage", "true"); 
    java.lang.System.setProperty("org.evosuite.shaded.org.dom4j.DocumentFactory.singleton.strategy", "org.evosuite.shaded.org.dom4j.util.SimpleSingleton"); 
    java.lang.System.setProperty("ctg_schedule", "BUDGET"); 
    java.lang.System.setProperty("sun.io.unicode.encoding", "UnicodeLittle"); 
    java.lang.System.setProperty("stopping_condition", "MAXTIME"); 
    java.lang.System.setProperty("print_to_system", "false"); 
    java.lang.System.setProperty("ctg_seeds_file_in", "/home/agudek/Documents/STRE/final_project/jfinal/.evosuite/evosuite-seeds/com.jfinal.render.Render.seed"); 
    java.lang.System.setProperty("output_variables", "TARGET_CLASS,configuration_id,criterion,ctg_min_time_per_job,ctg_schedule,search_budget,p_object_pool,ctg_time_per_class,Size,Length,Total_Time,Random_Seed,LineCoverage,LineCoverageBitString,BranchCoverage,BranchCoverageBitString,ExceptionCoverage,ExceptionCoverageBitString,Explicit_MethodExceptions,Explicit_TypeExceptions,Implicit_MethodExceptions,Implicit_TypeExceptions,WeakMutationScore,WeakMutationCoverageBitString,OutputCoverage,OutputCoverageBitString,MethodCoverage,MethodCoverageBitString,MethodNoExceptionCoverage,MethodNoExceptionCoverageBitString,CBranchCoverage,CBranchCoverageBitString"); 
    java.lang.System.setProperty("global_timeout", "40"); 
    java.lang.System.setProperty("assertions", "true"); 
    java.lang.System.setProperty("log_timeout", "false"); 
    java.lang.System.setProperty("master_log_port", "36025"); 
    java.lang.System.setProperty("reset_static_fields", "true"); 
    java.lang.System.setProperty("sun.java.command", "org.evosuite.ClientProcess"); 
    java.lang.System.setProperty("junit_check", "true"); 
    java.lang.System.setProperty("evosuite.log.folder", "/home/agudek/Documents/STRE/final_project/jfinal/.evosuite/tmp_2018_04_18_12_08_53/logs/com.jfinal.render.Render"); 
    java.lang.System.setProperty("minimize", "true"); 
    java.lang.System.setProperty("max_size", "100"); 
    java.lang.System.setProperty("sun.os.patch.level", "unknown"); 
    java.lang.System.setProperty("sun.cpu.endian", "little"); 
    java.lang.System.setProperty("ctg_min_time_per_job", "1"); 
    java.lang.System.setProperty("junit_suffix", "_ESTest"); 
    java.lang.System.setProperty("java.vendor.url.bug", "http://bugreport.sun.com/bugreport/"); 
    java.lang.System.setProperty("report_dir", "/home/agudek/Documents/STRE/final_project/jfinal/.evosuite/tmp_2018_04_18_12_08_53/reports/com.jfinal.render.Render"); 
    java.lang.System.setProperty("minimization_timeout", "6"); 
    java.lang.System.setProperty("CP_file_path", "/tmp/EvoSuite_classpathFile1574516742029159871.txt"); 
    java.lang.System.setProperty("java.rmi.server.hostname", "127.0.0.1"); 
    java.lang.System.setProperty("inline", "true"); 
    java.lang.System.setProperty("ctg_seeds_file_out", "/home/agudek/Documents/STRE/final_project/jfinal/.evosuite/tmp_2018_04_18_12_08_53/seeds/com.jfinal.render.Render.seed"); 
    java.lang.System.setProperty("TARGET_CLASS", "com.jfinal.render.Render"); 
    java.lang.System.setProperty("spawn_process_manager_port", "43787"); 
    java.lang.System.setProperty("evosuite.log.appender", "CLIENT"); 
    java.lang.System.setProperty("write_junit_timeout", "6"); 
    java.lang.System.setProperty("test_dir", "/home/agudek/Documents/STRE/final_project/jfinal/.evosuite/tmp_2018_04_18_12_08_53/tests"); 
    java.lang.System.setProperty("search_budget", "40"); 
    java.lang.System.setProperty("plot", "false"); 
    java.lang.System.setProperty("p_object_pool", "0.3"); 
    java.lang.System.setProperty("criterion", "LINE:BRANCH:EXCEPTION:WEAKMUTATION:OUTPUT:METHOD:METHODNOEXCEPTION:CBRANCH"); 
    java.lang.System.setProperty("test_comments", "false"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Render_ESTest_scaffolding.class.getClassLoader() ,
      "org.eclipse.jetty.server.Request",
      "org.eclipse.jetty.util.Attributes",
      "org.eclipse.jetty.util.component.LifeCycle",
      "com.google.zxing.qrcode.decoder.ErrorCorrectionLevel",
      "com.jfinal.render.Render",
      "com.jfinal.render.JsonRender",
      "org.apache.velocity.context.Context",
      "org.eclipse.jetty.server.handler.ContextHandler$Context",
      "com.jfinal.handler.Handler",
      "com.jfinal.render.JspRender",
      "org.apache.velocity.exception.VelocityException",
      "org.eclipse.jetty.util.log.Slf4jLog",
      "org.eclipse.jetty.io.Buffer",
      "org.eclipse.jetty.util.Loader",
      "com.jfinal.core.JFinal",
      "com.jfinal.render.TemplateRender",
      "org.eclipse.jetty.io.AbstractConnection",
      "com.jfinal.render.NullRender",
      "com.jfinal.render.RenderManager",
      "com.jfinal.render.IRenderFactory",
      "org.eclipse.jetty.util.log.JettyAwareLogger",
      "org.eclipse.jetty.server.AsyncContinuation$AsyncEventState",
      "com.jfinal.kit.StrKit",
      "org.eclipse.jetty.server.Response",
      "org.eclipse.jetty.continuation.Continuation",
      "com.jfinal.core.ActionHandler",
      "org.eclipse.jetty.server.AbstractHttpConnection",
      "org.eclipse.jetty.server.UserIdentity",
      "org.eclipse.jetty.io.nio.IndirectNIOBuffer",
      "org.eclipse.jetty.io.ByteArrayBuffer",
      "com.jfinal.template.Engine",
      "org.eclipse.jetty.continuation.ContinuationThrowable",
      "org.eclipse.jetty.http.HttpURI",
      "org.eclipse.jetty.io.nio.NIOBuffer",
      "org.eclipse.jetty.util.log.AbstractLogger",
      "com.jfinal.render.ErrorRender",
      "com.jfinal.render.VelocityRender",
      "org.eclipse.jetty.util.log.Log$1",
      "org.eclipse.jetty.server.UserIdentity$Scope",
      "com.jfinal.render.QrCodeRender",
      "org.eclipse.jetty.io.AbstractBuffer",
      "org.eclipse.jetty.util.MultiMap",
      "com.jfinal.render.JsonRender$1",
      "org.apache.velocity.exception.ParseErrorException",
      "com.jfinal.server.IServer",
      "org.eclipse.jetty.server.SessionManager",
      "org.eclipse.jetty.server.Authentication",
      "org.eclipse.jetty.server.Request$1",
      "com.jfinal.render.XmlRender",
      "org.eclipse.jetty.util.log.Log",
      "org.eclipse.jetty.io.Connection",
      "com.jfinal.plugin.activerecord.ModelRecordElResolver",
      "com.jfinal.render.RenderException",
      "org.eclipse.jetty.util.log.Logger",
      "org.eclipse.jetty.io.nio.DirectNIOBuffer",
      "org.apache.velocity.exception.ResourceNotFoundException",
      "org.eclipse.jetty.server.AsyncContinuation"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("javax.servlet.http.HttpServletRequest", false, Render_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("javax.servlet.http.HttpServletResponse", false, Render_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Render_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.jfinal.render.Render",
      "com.jfinal.render.ErrorRender",
      "com.jfinal.render.FileRender",
      "com.jfinal.render.JsonRender$1",
      "com.jfinal.render.JsonRender",
      "com.jfinal.render.TextRender",
      "com.jfinal.render.VelocityRender",
      "com.jfinal.core.JFinal",
      "com.jfinal.render.RedirectRender",
      "freemarker.core.Configurable",
      "freemarker.template.Version",
      "freemarker.template.TemplateExceptionHandler$1",
      "freemarker.template.TemplateExceptionHandler$2",
      "freemarker.template.TemplateExceptionHandler$3",
      "freemarker.template.TemplateExceptionHandler$4",
      "freemarker.template.TemplateExceptionHandler",
      "freemarker.core.ArithmeticEngine$BigDecimalEngine",
      "freemarker.core.ArithmeticEngine$ConservativeEngine",
      "freemarker.core.ArithmeticEngine",
      "freemarker.ext.beans.HashAdapter",
      "freemarker.ext.beans.SequenceAdapter",
      "freemarker.ext.beans.CollectionAdapter",
      "freemarker.ext.beans.SetAdapter",
      "freemarker.log.Logger",
      "freemarker.template.utility.ClassUtil",
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "freemarker.log._Log4JLoggerFactory",
      "freemarker.log._Log4JLoggerFactory$Log4JLogger",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.spi.RootLogger",
      "org.apache.log4j.Priority",
      "org.apache.log4j.Level",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.ProvisionNode",
      "freemarker.template.utility.SecurityUtilities",
      "freemarker.template.utility.SecurityUtilities$1",
      "freemarker.ext.beans.ClassBasedModelFactory",
      "freemarker.ext.beans._EnumModels",
      "freemarker.core._ConcurrentMapFactory",
      "freemarker.ext.beans.StaticModels",
      "freemarker.ext.util.ModelCache",
      "freemarker.ext.beans.BeansModelCache",
      "freemarker.template.SimpleScalar",
      "freemarker.ext.beans.BeanModel$1",
      "freemarker.ext.beans.BeanModel",
      "freemarker.ext.beans.BooleanModel",
      "freemarker.ext.beans.BeansWrapper$MethodSignature",
      "freemarker.ext.beans.BeansWrapper$MethodAppearanceDecision",
      "freemarker.ext.beans.OverloadedMethods",
      "freemarker.ext.beans.OverloadedMethodsSubset",
      "freemarker.ext.beans.OverloadedFixArgMethods",
      "freemarker.ext.beans.MethodUtilities",
      "freemarker.ext.beans.BeansWrapper$1",
      "freemarker.ext.beans.BeansWrapper$2",
      "freemarker.ext.beans.BeansWrapper$3",
      "freemarker.ext.beans.BeansWrapper",
      "freemarker.template.DefaultObjectWrapper",
      "freemarker.template.SimpleObjectWrapper",
      "freemarker.template.ObjectWrapper",
      "freemarker.core.TemplateClassResolver$1",
      "freemarker.core.TemplateClassResolver$2",
      "freemarker.core.TemplateClassResolver$3",
      "freemarker.core.TemplateClassResolver",
      "freemarker.template.utility.NullArgumentException",
      "freemarker.cache.TemplateCache",
      "freemarker.cache.FileTemplateLoader",
      "freemarker.cache.FileTemplateLoader$1",
      "freemarker.cache.SoftCacheStorage",
      "freemarker.template.utility.CaptureOutput",
      "freemarker.template.utility.StandardCompress",
      "freemarker.template.utility.HtmlEscape",
      "freemarker.template.utility.NormalizeNewlines",
      "freemarker.template.utility.XmlEscape",
      "freemarker.template.Configuration",
      "com.jfinal.render.FreeMarkerRender",
      "freemarker.cache.WebappTemplateLoader",
      "com.jfinal.render.TemplateRender",
      "com.jfinal.render.XmlRender",
      "com.jfinal.kit.StrKit",
      "com.jfinal.render.QrCodeRender",
      "com.jfinal.render.NullRender",
      "org.apache.velocity.app.Velocity",
      "org.apache.velocity.runtime.RuntimeInstance",
      "org.apache.velocity.runtime.log.Log",
      "org.apache.velocity.runtime.log.HoldingLogChute",
      "org.apache.commons.collections.ExtendedProperties",
      "org.apache.velocity.runtime.VelocimacroFactory",
      "org.apache.velocity.runtime.log.LogDisplayWrapper",
      "org.apache.velocity.runtime.VelocimacroManager",
      "org.apache.velocity.util.MapFactory",
      "org.apache.velocity.util.introspection.IntrospectorBase",
      "org.apache.velocity.util.introspection.Introspector",
      "org.apache.velocity.util.introspection.IntrospectorCacheImpl",
      "org.apache.velocity.runtime.RuntimeSingleton",
      "org.apache.commons.collections.ExtendedProperties$PropertiesReader",
      "org.apache.commons.collections.ExtendedProperties$PropertiesTokenizer",
      "org.apache.velocity.runtime.log.LogManager",
      "org.apache.velocity.util.ClassUtils",
      "org.apache.velocity.runtime.log.Log4JLogChute",
      "org.apache.velocity.util.StringUtils",
      "org.apache.log4j.Layout",
      "org.apache.log4j.PatternLayout",
      "org.apache.log4j.helpers.PatternParser",
      "org.apache.log4j.helpers.FormattingInfo",
      "org.apache.log4j.helpers.AbsoluteTimeDateFormat",
      "org.apache.log4j.helpers.ISO8601DateFormat",
      "org.apache.log4j.helpers.PatternConverter",
      "org.apache.log4j.helpers.PatternParser$DatePatternConverter",
      "org.apache.log4j.helpers.PatternParser$LiteralPatternConverter",
      "org.apache.log4j.helpers.PatternParser$BasicPatternConverter",
      "org.apache.log4j.AppenderSkeleton",
      "org.apache.log4j.WriterAppender",
      "org.apache.log4j.FileAppender",
      "org.apache.log4j.RollingFileAppender",
      "org.apache.log4j.helpers.OnlyOnceErrorHandler",
      "org.apache.log4j.helpers.QuietWriter",
      "org.apache.log4j.helpers.CountingQuietWriter",
      "org.apache.log4j.helpers.AppenderAttachableImpl",
      "org.apache.velocity.runtime.resource.ResourceManagerImpl",
      "org.apache.velocity.runtime.resource.loader.ResourceLoaderFactory",
      "org.apache.velocity.runtime.resource.loader.ResourceLoader",
      "org.apache.velocity.runtime.resource.loader.FileResourceLoader",
      "org.apache.velocity.runtime.resource.ResourceCacheImpl",
      "org.apache.commons.lang.StringUtils",
      "org.apache.commons.collections.map.AbstractHashedMap",
      "org.apache.commons.collections.map.AbstractLinkedMap",
      "org.apache.commons.collections.map.LRUMap",
      "org.apache.commons.collections.map.AbstractHashedMap$HashEntry",
      "org.apache.commons.collections.map.AbstractLinkedMap$LinkEntry",
      "org.apache.velocity.runtime.directive.Directive",
      "org.apache.velocity.runtime.directive.StopCommand",
      "org.apache.velocity.runtime.directive.Stop",
      "org.apache.velocity.runtime.directive.Block",
      "org.apache.velocity.runtime.directive.Define",
      "org.apache.velocity.runtime.directive.Break",
      "org.apache.velocity.runtime.directive.Evaluate",
      "org.apache.velocity.runtime.directive.Literal",
      "org.apache.velocity.runtime.directive.Macro",
      "org.apache.velocity.runtime.directive.InputBase",
      "org.apache.velocity.runtime.directive.Parse",
      "org.apache.velocity.runtime.directive.Include",
      "org.apache.velocity.runtime.directive.Foreach",
      "org.apache.velocity.app.event.EventCartridge",
      "org.apache.velocity.runtime.ParserPoolImpl",
      "org.apache.velocity.util.SimplePool",
      "org.apache.velocity.runtime.parser.Parser",
      "org.apache.velocity.runtime.parser.VelocityCharStream",
      "org.apache.velocity.runtime.parser.JJTParserState",
      "org.apache.velocity.runtime.parser.Parser$LookaheadSuccess",
      "org.apache.velocity.runtime.parser.ParserTokenManager",
      "org.apache.commons.lang.text.StrBuilder",
      "org.apache.velocity.runtime.parser.Token",
      "org.apache.velocity.runtime.parser.Parser$JJCalls",
      "org.apache.velocity.util.introspection.UberspectImpl",
      "org.apache.velocity.context.InternalContextBase",
      "org.apache.velocity.context.AbstractContext",
      "org.apache.velocity.VelocityContext",
      "com.jfinal.render.RenderException",
      "com.jfinal.render.JavascriptRender",
      "com.jfinal.plugin.activerecord.ModelRecordElResolver",
      "com.jfinal.render.JspRender",
      "com.jfinal.kit.JsonKit",
      "com.jfinal.json.JFinalJsonFactory",
      "com.jfinal.json.Json",
      "com.jfinal.json.JFinalJson",
      "com.jfinal.render.RenderManager",
      "com.jfinal.render.HtmlRender",
      "com.jfinal.template.EngineConfig",
      "com.jfinal.template.io.WriterBuffer",
      "com.jfinal.template.io.EncoderFactory",
      "com.jfinal.template.io.WriterBuffer$1",
      "com.jfinal.template.io.WriterBuffer$2",
      "com.jfinal.template.io.WriterBuffer$3",
      "com.jfinal.template.OutputDirectiveFactory",
      "com.jfinal.template.source.FileSourceFactory",
      "com.jfinal.template.expr.ast.SharedMethodKit",
      "com.jfinal.template.ext.sharedmethod.SharedMethodLib",
      "com.jfinal.template.ext.extensionmethod.StringExt",
      "com.jfinal.template.expr.ast.MethodKit",
      "com.jfinal.template.Engine",
      "freemarker.template.TemplateException",
      "freemarker.core._MiscTemplateException",
      "freemarker.core.Configurable$UnknownSettingException",
      "freemarker.core.Environment$6",
      "freemarker.core.Environment",
      "freemarker.core._DelayedConversionToString",
      "freemarker.core._DelayedJQuote",
      "freemarker.core._ErrorDescriptionBuilder",
      "org.apache.struts.mock.MockServletContext",
      "org.apache.commons.logging.impl.Log4JLogger",
      "org.eclipse.jetty.util.log.Log$1",
      "org.eclipse.jetty.util.log.Log",
      "org.eclipse.jetty.util.Loader",
      "org.eclipse.jetty.util.log.AbstractLogger",
      "org.eclipse.jetty.util.log.Slf4jLog",
      "org.eclipse.jetty.util.log.JettyAwareLogger",
      "org.eclipse.jetty.util.component.AbstractLifeCycle",
      "org.eclipse.jetty.util.component.AggregateLifeCycle",
      "org.eclipse.jetty.server.handler.AbstractHandler",
      "org.eclipse.jetty.server.handler.AbstractHandlerContainer",
      "org.eclipse.jetty.server.handler.HandlerWrapper",
      "org.eclipse.jetty.server.handler.ScopedHandler",
      "org.eclipse.jetty.server.session.SessionHandler",
      "org.eclipse.jetty.security.SecurityHandler$2",
      "org.eclipse.jetty.security.SecurityHandler$3",
      "org.eclipse.jetty.security.SecurityHandler",
      "org.eclipse.jetty.security.ConstraintSecurityHandler",
      "org.eclipse.jetty.security.DefaultAuthenticatorFactory",
      "org.eclipse.jetty.http.PathMap",
      "org.eclipse.jetty.util.StringMap",
      "org.eclipse.jetty.util.StringMap$Node",
      "org.eclipse.jetty.servlet.ServletHandler",
      "org.eclipse.jetty.server.handler.ErrorHandler",
      "org.eclipse.jetty.server.handler.ContextHandler",
      "org.eclipse.jetty.servlet.ServletContextHandler",
      "org.eclipse.jetty.webapp.WebAppContext",
      "org.eclipse.jetty.util.AttributesMap",
      "org.eclipse.jetty.server.handler.ContextHandler$Context",
      "org.eclipse.jetty.servlet.ServletContextHandler$Context",
      "org.eclipse.jetty.webapp.MetaData",
      "org.eclipse.jetty.webapp.WebAppContext$Context",
      "freemarker.ext.beans.StringModel$1",
      "freemarker.ext.beans.StringModel",
      "freemarker.ext.beans.SimpleMemberModel",
      "com.jfinal.render.Redirect301Render",
      "freemarker.ext.servlet.FreemarkerServlet",
      "com.jfinal.render.JsonRender$2",
      "org.eclipse.jetty.servlet.ErrorPageErrorHandler",
      "org.eclipse.jetty.server.Request",
      "org.eclipse.jetty.continuation.ContinuationThrowable",
      "org.eclipse.jetty.server.AsyncContinuation",
      "com.alibaba.druid.pool.WrapperAdapter",
      "com.alibaba.druid.support.logging.Resources",
      "com.alibaba.druid.support.logging.Log4jImpl",
      "com.alibaba.druid.support.logging.LogFactory",
      "com.alibaba.druid.pool.DruidAbstractDataSource",
      "com.alibaba.druid.pool.DruidDataSource",
      "com.alibaba.druid.util.Histogram",
      "com.alibaba.druid.pool.DruidDataSourceStatLoggerAdapter",
      "com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl",
      "com.alibaba.druid.util.Utils",
      "org.eclipse.jetty.io.AbstractConnection",
      "org.eclipse.jetty.server.AbstractHttpConnection",
      "org.eclipse.jetty.server.AbstractConnector",
      "org.eclipse.jetty.server.LocalConnector",
      "org.eclipse.jetty.util.statistic.CounterStatistic",
      "org.eclipse.jetty.util.statistic.SampleStatistic",
      "org.eclipse.jetty.http.HttpBuffersImpl",
      "org.eclipse.jetty.util.component.AggregateLifeCycle$Bean",
      "org.eclipse.jetty.io.ByteArrayEndPoint",
      "org.eclipse.jetty.io.AbstractBuffer",
      "org.eclipse.jetty.io.ByteArrayBuffer",
      "org.eclipse.jetty.server.Server",
      "org.eclipse.jetty.util.component.Container",
      "org.eclipse.jetty.util.LazyList",
      "org.eclipse.jetty.server.BlockingHttpConnection",
      "org.eclipse.jetty.util.URIUtil",
      "org.eclipse.jetty.http.HttpURI",
      "org.eclipse.jetty.util.Utf8Appendable",
      "org.eclipse.jetty.util.Utf8StringBuilder",
      "org.eclipse.jetty.http.HttpParser$EventHandler",
      "org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler",
      "org.eclipse.jetty.http.HttpParser",
      "org.eclipse.jetty.io.View",
      "org.eclipse.jetty.io.View$CaseInsensitive",
      "org.eclipse.jetty.util.DateCache",
      "org.eclipse.jetty.io.BufferDateCache",
      "org.eclipse.jetty.http.HttpFields$1",
      "org.eclipse.jetty.http.HttpFields$2",
      "org.eclipse.jetty.http.HttpFields$DateGenerator",
      "org.eclipse.jetty.util.StringUtil",
      "org.eclipse.jetty.util.StringMap$NullEntry",
      "org.eclipse.jetty.http.HttpFields",
      "org.eclipse.jetty.server.Response",
      "org.eclipse.jetty.http.AbstractGenerator",
      "org.eclipse.jetty.io.BufferCache",
      "org.eclipse.jetty.io.ByteArrayBuffer$CaseInsensitive",
      "org.eclipse.jetty.io.BufferCache$CachedBuffer",
      "org.eclipse.jetty.http.HttpVersions",
      "org.eclipse.jetty.http.HttpStatus$Code",
      "org.eclipse.jetty.http.HttpStatus",
      "org.eclipse.jetty.http.HttpGenerator$Status",
      "org.eclipse.jetty.http.HttpGenerator",
      "org.eclipse.jetty.server.nio.AbstractNIOConnector",
      "org.eclipse.jetty.server.nio.SelectChannelConnector",
      "org.eclipse.jetty.io.nio.SelectorManager",
      "org.eclipse.jetty.server.nio.SelectChannelConnector$ConnectorSelectorManager",
      "org.eclipse.jetty.util.component.Container$Relationship",
      "org.eclipse.jetty.server.AsyncHttpConnection",
      "org.eclipse.jetty.server.session.AbstractSessionManager$1",
      "org.eclipse.jetty.server.session.AbstractSessionManager",
      "org.eclipse.jetty.server.session.HashSessionManager",
      "org.eclipse.jetty.server.session.AbstractSessionManager$2",
      "org.eclipse.jetty.util.resource.Resource",
      "org.eclipse.jetty.util.resource.ResourceCollection",
      "org.eclipse.jetty.http.HttpHeaders",
      "freemarker.template.SimpleNumber",
      "com.alibaba.druid.sql.ast.SQLObjectImpl",
      "com.alibaba.druid.sql.ast.statement.SQLSelectQueryBlock",
      "org.eclipse.jetty.util.MultiMap",
      "org.eclipse.jetty.util.UrlEncoded",
      "org.eclipse.jetty.http.MimeTypes",
      "org.eclipse.jetty.io.SimpleBuffers",
      "com.alibaba.druid.util.jdbc.ConnectionBase",
      "com.alibaba.druid.mock.MockConnection",
      "org.eclipse.jetty.util.TypeUtil",
      "com.mchange.v2.c3p0.impl.AbstractIdentityTokenized",
      "com.mchange.v2.c3p0.impl.IdentityTokenResolvable",
      "com.mchange.v2.log.MLogConfig",
      "com.mchange.v2.cfg.MLogConfigSource",
      "com.mchange.v2.cfg.ConfigUtils",
      "com.mchange.v2.cfg.DelayedLogItem",
      "com.mchange.v2.cfg.DelayedLogItem$Level",
      "com.mchange.v2.cfg.MultiPropertiesConfig",
      "com.mchange.v2.cfg.BasicMultiPropertiesConfig",
      "com.mchange.v2.cfg.BasicPropertiesConfigSource",
      "com.mchange.v2.cfg.PropertiesConfigSource$Parse",
      "com.mchange.v2.cfg.BasicMultiPropertiesConfig$SystemPropertiesConfigSource",
      "com.mchange.v2.log.MLogClasses",
      "com.mchange.v2.log.MLevel",
      "com.mchange.v2.log.slf4j.Slf4jMLog",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$TraceLogger",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$DebugLogger",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$InfoLogger",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$WarnLogger",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$ErrorLogger",
      "com.mchange.v2.log.slf4j.Slf4jMLog$Slf4jMLogger$OffLogger",
      "com.mchange.v2.log.MLog$1",
      "com.mchange.v2.log.MLog",
      "com.mchange.v2.naming.JavaBeanReferenceMaker",
      "com.mchange.v2.naming.ReferenceIndirector",
      "com.mchange.v2.c3p0.impl.DriverManagerDataSourceBase",
      "com.alibaba.druid.proxy.DruidDriver$1",
      "com.alibaba.druid.proxy.DruidDriver",
      "com.alibaba.druid.mock.handler.MySqlMockExecuteHandlerImpl",
      "com.alibaba.druid.mock.MockDriver",
      "org.hsqldb.jdbc.JDBCDriver",
      "com.mchange.v2.c3p0.DriverManagerDataSource",
      "com.mchange.v2.c3p0.impl.C3P0Defaults",
      "com.mchange.v2.cfg.MConfig$CSManager",
      "com.mchange.v1.cachedstore.CachedStoreFactory",
      "com.mchange.v1.cachedstore.NoCleanupCachedStore",
      "com.mchange.v1.cachedstore.CachedStoreUtils",
      "com.mchange.v1.lang.Synchronizer",
      "com.mchange.v1.lang.Synchronizer$1",
      "com.mchange.v2.cfg.MConfig",
      "com.mchange.v2.cfg.MConfig$PathsKey",
      "com.mchange.v1.util.ArrayUtils",
      "com.mchange.v2.lang.ObjectUtils",
      "com.mchange.v2.c3p0.cfg.C3P0ConfigXmlUtils",
      "com.mchange.v2.c3p0.cfg.DefaultC3P0ConfigFinder",
      "com.mchange.v2.c3p0.cfg.C3P0ConfigUtils",
      "com.mchange.v2.lang.Coerce",
      "com.mchange.v2.c3p0.cfg.NamedScope",
      "com.mchange.v2.c3p0.cfg.C3P0Config",
      "com.mchange.v1.lang.BooleanUtils",
      "com.mchange.v2.c3p0.impl.AuthMaskingProperties",
      "com.mchange.v2.c3p0.DriverManagerDataSource$1",
      "com.alibaba.druid.util.jdbc.StatementBase",
      "com.alibaba.druid.util.jdbc.PreparedStatementBase",
      "com.alibaba.druid.mock.MockPreparedStatement",
      "com.alibaba.druid.mock.MockCallableStatement",
      "com.alibaba.druid.mock.MockParameterMetaData",
      "com.alibaba.druid.util.jdbc.ResultSetMetaDataBase",
      "com.alibaba.druid.mock.MockResultSetMetaData",
      "com.alibaba.druid.util.jdbc.ResultSetBase",
      "com.alibaba.druid.mock.MockResultSet",
      "org.eclipse.jetty.io.AbstractBuffers",
      "org.eclipse.jetty.io.ThreadLocalBuffers",
      "org.eclipse.jetty.io.ThreadLocalBuffers$1",
      "com.jfinal.core.JFinalFilter",
      "com.mchange.v2.c3p0.JndiRefConnectionPoolDataSource",
      "com.mchange.v2.c3p0.impl.JndiRefDataSourceBase",
      "com.mchange.v2.c3p0.JndiRefForwardingDataSource",
      "com.mchange.v2.c3p0.impl.DbAuth",
      "com.mchange.v2.log.jdk14logging.ForwardingLogger",
      "com.mchange.v1.identicator.IdentityHashCodeIdenticator",
      "com.mchange.v2.encounter.EncounterUtils",
      "com.mchange.v2.encounter.AbstractEncounterCounter",
      "com.mchange.v2.encounter.GenericEncounterCounter",
      "com.mchange.v1.identicator.IdMap",
      "com.mchange.v1.identicator.IdWeakHashMap",
      "com.mchange.v2.encounter.EncounterUtils$1",
      "com.mchange.v2.uid.UidUtils",
      "com.mchange.v2.c3p0.impl.C3P0ImplUtils",
      "com.mchange.v1.identicator.IdHashKey",
      "com.mchange.v1.identicator.WeakIdHashKey",
      "com.mchange.v1.identicator.WeakIdHashKey$Ref",
      "com.mchange.v2.c3p0.impl.IdentityTokenizedCoalesceChecker",
      "com.mchange.v2.coalesce.CoalescerFactory",
      "com.mchange.v2.coalesce.AbstractWeakCoalescer",
      "com.mchange.v2.coalesce.WeakCcCoalescer",
      "com.mchange.v2.coalesce.CoalesceIdenticator",
      "com.mchange.v2.util.DoubleWeakHashMap",
      "com.mchange.v2.util.DoubleWeakHashMap$CheckKeyHolder",
      "com.mchange.v2.c3p0.AbstractConnectionTester",
      "com.mchange.v2.c3p0.impl.DefaultConnectionTester$1",
      "com.mchange.v2.c3p0.impl.DefaultConnectionTester$2",
      "com.mchange.v2.c3p0.impl.DefaultConnectionTester$3",
      "com.mchange.v2.c3p0.impl.ThreadLocalQuerylessTestRunner$1",
      "com.mchange.v2.c3p0.impl.ThreadLocalQuerylessTestRunner",
      "com.mchange.v2.c3p0.impl.DefaultConnectionTester",
      "com.mchange.v2.c3p0.management.ActiveManagementCoordinator",
      "com.mchange.v2.c3p0.C3P0Registry",
      "com.mchange.v2.util.DoubleWeakHashMap$UserKeySet",
      "com.mchange.v2.util.DoubleWeakHashMap$WKey",
      "com.mchange.v2.util.DoubleWeakHashMap$WVal",
      "com.mchange.v2.c3p0.JndiRefForwardingDataSource$1",
      "com.mchange.v2.c3p0.JndiRefForwardingDataSource$2",
      "com.mchange.v2.c3p0.impl.WrapperConnectionPoolDataSourceBase",
      "com.mchange.v2.c3p0.WrapperConnectionPoolDataSource",
      "com.mchange.v2.c3p0.WrapperConnectionPoolDataSource$1",
      "com.alibaba.druid.pool.DruidDataSourceC3P0Adapter",
      "org.eclipse.jetty.io.nio.IndirectNIOBuffer",
      "org.eclipse.jetty.io.nio.SslConnection",
      "com.alibaba.druid.sql.ast.expr.SQLAggregateOption",
      "com.jfinal.template.source.ClassPathSourceFactory",
      "org.eclipse.jetty.io.PooledBuffers",
      "com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase",
      "com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource",
      "com.mchange.v2.c3p0.AbstractComboPooledDataSource",
      "com.mchange.v2.c3p0.ComboPooledDataSource",
      "com.mchange.v2.c3p0.management.C3P0RegistryManager",
      "com.mchange.v2.management.ManagementUtils$1",
      "com.mchange.v2.management.ManagementUtils$2",
      "com.mchange.v2.management.ManagementUtils",
      "com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean",
      "com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean$1",
      "com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource$1",
      "com.mchange.v2.c3p0.AbstractComboPooledDataSource$1",
      "com.mchange.v2.c3p0.AbstractComboPooledDataSource$2",
      "com.mchange.v2.c3p0.impl.C3P0PooledConnectionPoolManager",
      "com.mchange.v2.async.ThreadPoolAsynchronousRunner",
      "com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector",
      "com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread",
      "com.mchange.v2.resourcepool.ResourcePoolFactory",
      "com.mchange.v2.resourcepool.BasicResourcePoolFactory",
      "com.mchange.v2.beans.BeansUtils",
      "com.alibaba.druid.mock.MockStatement",
      "com.alibaba.druid.mock.MockSavepoint",
      "org.eclipse.jetty.webapp.AbstractConfiguration",
      "org.eclipse.jetty.webapp.WebInfConfiguration",
      "org.eclipse.jetty.security.authentication.LoginAuthenticator",
      "org.eclipse.jetty.security.authentication.BasicAuthenticator",
      "org.eclipse.jetty.util.QuotedStringTokenizer",
      "org.eclipse.jetty.http.HttpFields$Field",
      "com.jfinal.ext.interceptor.SessionInViewInterceptor$JFinalSession",
      "org.eclipse.jetty.http.HttpHeaderValues",
      "org.eclipse.jetty.server.HttpOutput",
      "org.eclipse.jetty.server.AbstractHttpConnection$Output",
      "org.eclipse.jetty.server.HttpWriter",
      "org.eclipse.jetty.server.AbstractHttpConnection$OutputWriter",
      "org.eclipse.jetty.server.AbstractHttpConnection$1",
      "org.eclipse.jetty.util.ByteArrayOutputStream2",
      "freemarker.ext.beans.OverloadedVarargMethods",
      "freemarker.ext.beans.OverloadedVarargMethods$ArgumentPacker",
      "org.apache.struts.mock.MockHttpSession",
      "org.eclipse.jetty.server.Authentication$1",
      "org.eclipse.jetty.server.Authentication$2",
      "org.eclipse.jetty.server.Authentication$3",
      "org.eclipse.jetty.server.Authentication$4",
      "org.eclipse.jetty.server.Authentication$5",
      "org.eclipse.jetty.server.Authentication",
      "freemarker.ext.beans.NumberModel$1",
      "freemarker.ext.beans.NumberModel",
      "com.alibaba.druid.util.StringUtils",
      "org.eclipse.jetty.util.resource.URLResource",
      "org.eclipse.jetty.util.resource.FileResource",
      "org.eclipse.jetty.io.AbstractBuffers$1",
      "com.alibaba.druid.mock.MockClob",
      "com.oreilly.servlet.MultipartFilter",
      "org.eclipse.jetty.server.session.JDBCSessionManager",
      "org.springframework.jndi.JndiTemplate",
      "org.eclipse.jetty.webapp.ClasspathPattern",
      "org.eclipse.jetty.webapp.ClasspathPattern$Entry",
      "org.eclipse.jetty.server.handler.ContextHandler$CLDump",
      "org.eclipse.jetty.servlet.Holder",
      "org.eclipse.jetty.servlet.ServletHolder",
      "org.eclipse.jetty.servlet.FilterHolder",
      "org.eclipse.jetty.servlet.FilterMapping",
      "org.eclipse.jetty.server.session.AbstractSession",
      "org.eclipse.jetty.server.session.HashedSession",
      "org.eclipse.jetty.util.resource.JarResource",
      "org.apache.jasper.servlet.JspCServletContext",
      "com.alibaba.druid.mock.MockNClob",
      "com.alibaba.druid.pool.DruidConnectionHolder",
      "com.alibaba.druid.pool.PoolableWrapper",
      "com.alibaba.druid.pool.DruidPooledConnection",
      "org.springframework.util.CustomizableThreadCreator",
      "org.springframework.scheduling.concurrent.CustomizableThreadFactory",
      "org.springframework.scheduling.concurrent.ExecutorConfigurationSupport",
      "org.springframework.util.ClassUtils",
      "org.springframework.util.Assert",
      "org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler",
      "org.springframework.util.StringUtils",
      "com.alibaba.druid.pool.DruidPooledPreparedStatement$PreparedStatementKey",
      "org.eclipse.jetty.server.HttpInput",
      "com.alibaba.druid.util.JdbcUtils"
    );
  }
}
