/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 18:12:36 GMT 2018
 */

package com.jfinal.render;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jfinal.render.XmlRender;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class XmlRender_ESTest extends XmlRender_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlRender xmlRender0 = new XmlRender("");
      String string0 = xmlRender0.getContentType();
      assertEquals("text/xml; charset=UTF-8", string0);
  }
}
