/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 18 14:57:00 GMT 2018
 */

package com.jfinal.template.expr.ast;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jfinal.template.expr.ast.Expr;
import com.jfinal.template.expr.ast.ExprList;
import com.jfinal.template.expr.ast.StaticMethod;
import com.jfinal.template.stat.Location;
import com.jfinal.template.stat.Scope;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true)
public class StaticMethod_ESTest extends StaticMethod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Location location0 = new Location("hDP}Vzq<9,Oz^&r}O", 34);
      StaticMethod staticMethod0 = null;
      try {
        staticMethod0 = new StaticMethod((String) null, (String) null, location0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // null
         // Template: \"hDP}Vzq<9,Oz^&r}O\". Line: 34
         //
         verifyException("com.jfinal.template.expr.ast.StaticMethod", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Location location0 = new Location("Not public static method: ", 1118);
      StaticMethod staticMethod0 = new StaticMethod("com.jfinal.template.expr.ast.StaticMethod", "Not public static method: ", location0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<Expr> linkedList0 = new LinkedList<Expr>();
      ExprList exprList0 = ExprList.NULL_EXPR_LIST;
      linkedList0.add((Expr) exprList0);
      ExprList exprList1 = new ExprList(linkedList0);
      Location location0 = new Location("com.jfinal.template.expr.ast.StaticMethod", 373);
      StaticMethod staticMethod0 = new StaticMethod("com.jfinal.template.expr.ast.StaticMethod", "com.jfinal.template.expr.ast.StaticMethod", exprList1, location0);
      // Undeclared exception!
      try { 
        staticMethod0.eval((Scope) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class com.jfinal.template.expr.ast.MethodKit
         //
         verifyException("com.jfinal.template.expr.ast.StaticMethod", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Location location0 = new Location("com.jfinal.template.expr.ast.MethodKit", 2);
      StaticMethod staticMethod0 = null;
      try {
        staticMethod0 = new StaticMethod("com.jfinal.template.expr.ast.MethodKit", "com.jfinal.template.expr.ast.MethodKit", location0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LinkedList<Expr> linkedList0 = new LinkedList<Expr>();
      linkedList0.add((Expr) null);
      ExprList exprList0 = new ExprList(linkedList0);
      Location location0 = new Location("com.jfinal.template.expr.ast.StaticMethod", 373);
      StaticMethod staticMethod0 = new StaticMethod("com.jfinal.template.expr.ast.StaticMethod", "com.jfinal.template.expr.ast.StaticMethod", exprList0, location0);
      // Undeclared exception!
      try { 
        staticMethod0.eval((Scope) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jfinal.template.expr.ast.ExprList", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ExprList exprList0 = ExprList.NULL_EXPR_LIST;
      Location location0 = new Location("8", 1);
      StaticMethod staticMethod0 = null;
      try {
        staticMethod0 = new StaticMethod("8", "8", exprList0, location0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // exprList can not be blank
         // Template: \"8\". Line: 1
         //
         verifyException("com.jfinal.template.expr.ast.StaticMethod", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Location location0 = new Location("U#w4nZ,X]vubyl", 22);
      StaticMethod staticMethod0 = null;
      try {
        staticMethod0 = new StaticMethod("U#w4nZ,X]vubyl", "U#w4nZ,X]vubyl", (ExprList) null, location0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // exprList can not be blank
         // Template: \"U#w4nZ,X]vubyl\". Line: 22
         //
         verifyException("com.jfinal.template.expr.ast.StaticMethod", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Location location0 = new Location("", 0);
      StaticMethod staticMethod0 = null;
      try {
        staticMethod0 = new StaticMethod("", "cQ#3-O'%$NP'2N|", location0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Class not found: 
         // Template: \"\". Line: 0
         //
         verifyException("com.jfinal.template.expr.ast.StaticMethod", e);
      }
  }
}
