/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 23 09:03:41 GMT 2018
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.parser.Token;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Token_ESTest extends Token_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Token.TokenType.values();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = (Token.StartTag)token_StartTag0.reset();
      Token.StartTag token_StartTag2 = token_StartTag1.asStartTag();
      token_StartTag1.appendAttributeName("5}");
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("]]>", "]]>", attributes0);
      Attributes attributes1 = attributes0.put(attribute0);
      Attributes attributes2 = attributes1.clone();
      Attributes attributes3 = attributes2.put("]]>", true);
      attributes1.put("]]>", "5}");
      attributes2.remove("5}");
      Token.StartTag token_StartTag3 = token_StartTag2.nameAttr("5}", attributes3);
      token_StartTag3.toString();
      token_StartTag1.name();
      token_StartTag3.name("<5}  ]]>>");
      token_StartTag2.name();
      token_StartTag3.tokenType();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_StartTag1.isStartTag();
      token_StartTag3.normalName = "5}";
      token_StartTag2.appendAttributeValue("");
      // Undeclared exception!
      try { 
        token_StartTag1.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$StartTag cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      Token.Character token_Character0 = new Token.Character();
      token_Character0.getData();
      // Undeclared exception!
      try { 
        token_Character0.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Character cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.Doctype token_Doctype1 = token_Doctype0.asDoctype();
      // Undeclared exception!
      try { 
        token_Doctype1.asStartTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$StartTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Token.EOF token_EOF0 = new Token.EOF();
      token_EOF0.isEndTag();
      // Undeclared exception!
      try { 
        token_EOF0.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EOF cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.getName();
      // Undeclared exception!
      try { 
        token_Doctype0.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.Doctype token_Doctype1 = (Token.Doctype)token_Doctype0.reset();
      token_Doctype0.getPubSysKey();
      // Undeclared exception!
      try { 
        token_Doctype1.asComment();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$Comment
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Token.Character token_Character0 = new Token.Character();
      token_Character0.toString();
      Token.CData token_CData0 = new Token.CData((String) null);
      token_CData0.toString();
      token_CData0.toString();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.isForceQuirks();
      // Undeclared exception!
      try { 
        token_Character0.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Character cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.setEmptyAttributeValue();
      Token.StartTag token_StartTag1 = (Token.StartTag)token_StartTag0.reset();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.forceQuirks = false;
      token_Doctype0.reset();
      token_Doctype0.reset();
      token_StartTag0.finaliseTag();
      token_StartTag0.appendAttributeName("p1.HN6 ,[`0!g3v ");
      token_StartTag1.appendAttributeValue("p1.HN6 ,[`0!g3v ");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Token.EOF token_EOF0 = new Token.EOF();
      Token.EOF token_EOF1 = (Token.EOF)token_EOF0.reset();
      token_EOF1.isDoctype();
      token_EOF0.tokenType();
      Token.TokenType token_TokenType0 = Token.TokenType.Character;
      token_EOF0.type = token_TokenType0;
      token_EOF0.isEOF();
      token_EOF1.isCharacter();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Token.EOF token_EOF0 = new Token.EOF();
      token_EOF0.isEOF();
      // Undeclared exception!
      try { 
        token_EOF0.asStartTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EOF cannot be cast to org.jsoup.parser.Token$StartTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.reset((StringBuilder) null);
      token_Doctype0.pubSysKey = "selected";
      token_Doctype0.tokenType();
      Token.reset((StringBuilder) null);
      Token.Comment token_Comment0 = new Token.Comment();
      token_Comment0.toString();
      token_Comment0.getData();
      // Undeclared exception!
      try { 
        token_Doctype0.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.reset((StringBuilder) null);
      token_Doctype0.getSystemIdentifier();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.getPublicIdentifier();
      // Undeclared exception!
      try { 
        token_Doctype0.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = token_StartTag0.asStartTag();
      token_StartTag1.setEmptyAttributeValue();
      token_StartTag1.appendAttributeValue("");
      token_StartTag1.appendTagName('&');
      token_StartTag1.toString();
      int[] intArray0 = new int[7];
      intArray0[0] = 0;
      intArray0[1] = 6;
      intArray0[2] = 0;
      Token.TokenType token_TokenType0 = Token.TokenType.EOF;
      token_StartTag0.type = token_TokenType0;
      intArray0[3] = 0;
      intArray0[4] = 3416;
      intArray0[5] = 0;
      intArray0[6] = 1946;
      token_StartTag0.appendAttributeValue(intArray0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      String string0 = "Z\"sP";
      Token.EndTag token_EndTag1 = new Token.EndTag();
      token_EndTag0.selfClosing = false;
      token_EndTag1.appendAttributeValue('$');
      token_EndTag1.getAttributes();
      token_EndTag0.isCharacter();
      token_EndTag1.isSelfClosing();
      // Undeclared exception!
      try { 
        token_EndTag0.asComment();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EndTag cannot be cast to org.jsoup.parser.Token$Comment
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Token.Comment token_Comment0 = new Token.Comment();
      Token.Comment token_Comment1 = token_Comment0.asComment();
      Token.Comment token_Comment2 = (Token.Comment)token_Comment1.reset();
      Token.TokenType token_TokenType0 = Token.TokenType.StartTag;
      token_Comment2.type = token_TokenType0;
      // Undeclared exception!
      try { 
        token_Comment2.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Comment cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Token.Comment token_Comment0 = new Token.Comment();
      token_Comment0.bogus = false;
      token_Comment0.reset();
      token_Comment0.isDoctype();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Token.CData token_CData0 = new Token.CData("");
      Token.TokenType token_TokenType0 = Token.TokenType.Comment;
      token_CData0.type = token_TokenType0;
      token_CData0.toString();
      token_CData0.tokenType();
      Token.CData token_CData1 = (Token.CData)token_CData0.reset();
      token_CData0.isComment();
      token_CData1.tokenType();
      Token.TokenType.values();
      token_CData0.toString();
      // Undeclared exception!
      try { 
        token_CData1.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$CData cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Token.CData token_CData0 = new Token.CData("org.jsoup.parser.Token$EOF");
      Token.TokenType token_TokenType0 = Token.TokenType.Comment;
      token_CData0.type = token_TokenType0;
      token_CData0.data((String) null);
      token_CData0.isComment();
      token_CData0.isEndTag();
      // Undeclared exception!
      try { 
        token_CData0.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$CData cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      token_EndTag0.appendAttributeName("(l#6K1");
      token_EndTag0.tagName = "(l#6K1";
      token_EndTag0.appendAttributeName('c');
      token_EndTag0.toString();
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.name("]cz[CZ)j~\"uV(");
      token_EndTag1.asEndTag();
      // Undeclared exception!
      try { 
        token_EndTag1.asComment();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EndTag cannot be cast to org.jsoup.parser.Token$Comment
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.reset();
      char[] charArray0 = new char[2];
      charArray0[0] = '|';
      charArray0[1] = 'M';
      token_EndTag1.appendAttributeValue("$v}J)YFs>ua");
      token_EndTag1.appendAttributeValue(charArray0);
      // Undeclared exception!
      try { 
        token_EndTag1.asComment();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EndTag cannot be cast to org.jsoup.parser.Token$Comment
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      // Undeclared exception!
      try { 
        token_EndTag0.toString();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be false
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Token.CData token_CData0 = new Token.CData("Children collection to be inserted must not be null.");
      Token.CData token_CData1 = (Token.CData)token_CData0.reset();
      token_CData1.asCharacter();
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.normalName = "";
      Token.StartTag token_StartTag1 = token_StartTag0.nameAttr("", (Attributes) null);
      token_StartTag1.appendAttributeName("org.jsoup.parser.Token$EndTag");
      Token.TokenType token_TokenType0 = Token.TokenType.EOF;
      token_StartTag1.type = token_TokenType0;
      token_StartTag0.newAttribute();
      token_StartTag0.isEOF();
      token_StartTag0.setEmptyAttributeValue();
      token_StartTag0.appendTagName("org.jsoup.parser.Token$EndTag");
      token_StartTag1.appendAttributeValue("");
      token_StartTag1.appendAttributeName('D');
      token_StartTag0.finaliseTag();
      token_StartTag0.normalName();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.name("Dj@-ur;qfKcj'sQN\"");
      String string0 = null;
      char char0 = 'z';
      token_EndTag0.tokenType();
      // Undeclared exception!
      try { 
        token_EndTag1.appendTagName((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.appendAttributeName("");
      token_StartTag0.appendAttributeValue('B');
      token_StartTag0.appendAttributeName('C');
      token_StartTag0.tokenType();
      token_StartTag0.tokenType();
      token_StartTag0.appendAttributeValue("org.jsoup.parser.Token$1");
      token_StartTag0.appendAttributeName('-');
      token_StartTag0.newAttribute();
      // Undeclared exception!
      try { 
        token_StartTag0.name();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be false
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.appendAttributeName("");
      token_StartTag0.newAttribute();
      token_StartTag0.appendAttributeName('C');
      token_StartTag0.name("typemustmatch");
      token_StartTag0.tokenType();
      token_StartTag0.name();
      token_StartTag0.tokenType();
      token_StartTag0.appendAttributeValue("org.jsoup.parser.Token$1");
      token_StartTag0.appendAttributeName('-');
      token_StartTag0.newAttribute();
      token_StartTag0.name();
      // Undeclared exception!
      try { 
        Token.TokenType.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Name is null
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      int[] intArray0 = new int[4];
      intArray0[0] = 30;
      intArray0[1] = 0;
      intArray0[2] = (-593);
      intArray0[3] = 2410;
      // Undeclared exception!
      try { 
        token_StartTag0.appendAttributeValue(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.AbstractStringBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.setEmptyAttributeValue();
      // Undeclared exception!
      try { 
        token_StartTag0.appendAttributeValue((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.Token$Tag", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.reset();
      char[] charArray0 = new char[2];
      charArray0[0] = '|';
      charArray0[1] = 'M';
      token_EndTag1.appendAttributeValue(charArray0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.appendAttributeName("");
      token_StartTag0.appendAttributeName('C');
      token_StartTag0.name("typemustmatch");
      token_StartTag0.tokenType();
      token_StartTag0.tokenType();
      token_StartTag0.appendAttributeValue("org.jsoup.parser.Token$1");
      token_StartTag0.appendAttributeName('-');
      token_StartTag0.newAttribute();
      token_StartTag0.name();
      // Undeclared exception!
      try { 
        Token.TokenType.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Name is null
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Token.TokenType.values();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = (Token.StartTag)token_StartTag0.reset();
      Token.StartTag token_StartTag2 = token_StartTag1.asStartTag();
      token_StartTag1.appendAttributeName("5}");
      token_StartTag1.isStartTag();
      token_StartTag2.appendAttributeValue("");
      // Undeclared exception!
      try { 
        token_StartTag1.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$StartTag cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Token.TokenType.values();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.forceQuirks = false;
      token_Doctype0.tokenType();
      token_Doctype0.forceQuirks = true;
      Token.Doctype token_Doctype1 = token_Doctype0.asDoctype();
      token_Doctype1.pubSysKey = "Doctype";
      Token.TokenType token_TokenType0 = Token.TokenType.EOF;
      token_Doctype1.type = token_TokenType0;
      // Undeclared exception!
      try { 
        token_Doctype1.asComment();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$Comment
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Token.Doctype token_Doctype0 = new Token.Doctype();
      Token.Doctype token_Doctype1 = (Token.Doctype)token_Doctype0.reset();
      token_Doctype1.tokenType();
      token_Doctype1.isDoctype();
      // Undeclared exception!
      try { 
        token_Doctype1.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Doctype cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.setEmptyAttributeValue();
      token_StartTag0.appendAttributeValue(";B@f#XD=");
      token_StartTag0.appendTagName('H');
      token_StartTag0.name("=USv=r()M1pL9");
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Token.EOF token_EOF0 = new Token.EOF();
      token_EOF0.isStartTag();
      // Undeclared exception!
      try { 
        token_EOF0.asStartTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EOF cannot be cast to org.jsoup.parser.Token$StartTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.normalName = "";
      Token.StartTag token_StartTag1 = token_StartTag0.nameAttr("", (Attributes) null);
      Token.TokenType token_TokenType0 = Token.TokenType.EOF;
      token_StartTag1.type = token_TokenType0;
      token_StartTag0.newAttribute();
      token_StartTag0.isEOF();
      token_StartTag0.setEmptyAttributeValue();
      token_StartTag1.appendAttributeName('D');
      token_StartTag0.finaliseTag();
      token_StartTag0.normalName();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.name("vFt");
      Token.EndTag token_EndTag2 = token_EndTag1.asEndTag();
      Token.EndTag token_EndTag3 = (Token.EndTag)token_EndTag2.reset();
      token_EndTag3.newAttribute();
      token_EndTag3.isEndTag();
      token_EndTag2.isEndTag();
      token_EndTag2.appendAttributeName('.');
      token_EndTag2.newAttribute();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Token.Comment token_Comment0 = new Token.Comment();
      token_Comment0.toString();
      token_Comment0.isEOF();
      // Undeclared exception!
      try { 
        token_Comment0.asCharacter();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Comment cannot be cast to org.jsoup.parser.Token$Character
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = token_StartTag0.nameAttr("f{", (Attributes) null);
      Token.StartTag token_StartTag2 = token_StartTag1.asStartTag();
      token_StartTag2.toString();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Token.Character token_Character0 = new Token.Character();
      // Undeclared exception!
      try { 
        token_Character0.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Character cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      token_EndTag0.newAttribute();
      token_EndTag0.tokenType();
      token_EndTag0.appendAttributeName('\\');
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      String string0 = "Z\"sP";
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.name("Z\"sP");
      token_EndTag0.selfClosing = false;
      token_EndTag1.appendAttributeValue('$');
      token_EndTag1.getAttributes();
      token_EndTag0.isCharacter();
      token_EndTag1.isEndTag();
      // Undeclared exception!
      try { 
        token_EndTag0.asComment();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EndTag cannot be cast to org.jsoup.parser.Token$Comment
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Token.Character token_Character0 = new Token.Character();
      token_Character0.toString();
      token_Character0.asCharacter();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      char[] charArray0 = new char[8];
      charArray0[0] = 'I';
      charArray0[1] = 'G';
      charArray0[2] = 'H';
      charArray0[3] = '`';
      charArray0[4] = '/';
      charArray0[5] = '!';
      charArray0[6] = 'b';
      charArray0[7] = 'S';
      token_StartTag0.appendAttributeValue(charArray0);
      token_StartTag0.appendAttributeValue("k`}?Iwv-i%+:@-6v*<");
      token_StartTag0.appendAttributeValue((String) null);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      token_EndTag0.appendAttributeName("(l#6K1");
      token_EndTag0.tagName = "(l#6K1";
      token_EndTag0.toString();
      Token.EndTag token_EndTag1 = (Token.EndTag)token_EndTag0.name("]cz[CZ)j~\"uV(");
      Token.EndTag token_EndTag2 = token_EndTag1.asEndTag();
      token_EndTag1.newAttribute();
      Token.Comment token_Comment0 = new Token.Comment();
      token_Comment0.getData();
      Token.CData token_CData0 = new Token.CData("T?8:M5: j+`N");
      Token.TokenType token_TokenType0 = Token.TokenType.Doctype;
      token_CData0.type = token_TokenType0;
      token_CData0.reset();
      token_EndTag2.tokenType();
      int[] intArray0 = new int[9];
      intArray0[0] = 4;
      intArray0[1] = 1548;
      intArray0[2] = (-1);
      intArray0[3] = 1;
      intArray0[4] = 15;
      intArray0[5] = 30;
      intArray0[6] = 16;
      intArray0[7] = 3751;
      intArray0[8] = 25;
      // Undeclared exception!
      try { 
        token_EndTag2.appendAttributeValue(intArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.AbstractStringBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.getName();
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Token.Comment token_Comment0 = new Token.Comment();
      Token.Comment token_Comment1 = token_Comment0.asComment();
      StringBuilder stringBuilder0 = new StringBuilder("vFc`-7I\"rjJ");
      StringBuilder stringBuilder1 = stringBuilder0.deleteCharAt(6);
      StringBuilder stringBuilder2 = stringBuilder1.insert(6, '2');
      Token.reset(stringBuilder2);
      token_Comment0.toString();
      Token.Comment token_Comment2 = (Token.Comment)token_Comment1.reset();
      token_Comment1.tokenType();
      token_Comment0.tokenType();
      token_Comment0.tokenType();
      token_Comment2.tokenType();
      Token.reset(stringBuilder1);
      Token.TokenType token_TokenType0 = Token.TokenType.StartTag;
      token_Comment1.type = token_TokenType0;
      Token.Doctype token_Doctype0 = new Token.Doctype();
      StringBuilder stringBuilder3 = token_Doctype0.systemIdentifier;
      Token.reset(stringBuilder3);
      // Undeclared exception!
      try { 
        token_Comment0.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$Comment cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.normalName = "";
      Token.StartTag token_StartTag1 = token_StartTag0.nameAttr("", (Attributes) null);
      token_StartTag1.appendAttributeValue("");
      token_StartTag1.appendAttributeName("org.jsoup.parser.Token$EndTag");
      Token.TokenType token_TokenType0 = Token.TokenType.EOF;
      token_StartTag1.type = token_TokenType0;
      token_StartTag0.newAttribute();
      token_StartTag0.isEOF();
      int[] intArray0 = new int[1];
      intArray0[0] = 3171;
      token_StartTag0.appendAttributeValue(intArray0);
      token_StartTag0.setEmptyAttributeValue();
      token_StartTag0.appendTagName("org.jsoup.parser.Token$EndTag");
      token_StartTag1.appendAttributeValue("");
      char[] charArray0 = new char[9];
      charArray0[0] = '?';
      charArray0[1] = '(';
      charArray0[2] = 'g';
      charArray0[3] = 'F';
      charArray0[4] = ']';
      charArray0[5] = 'l';
      charArray0[6] = '>';
      charArray0[7] = ';';
      charArray0[8] = 'x';
      token_StartTag0.appendAttributeValue(charArray0);
      int[] intArray1 = new int[5];
      intArray1[0] = 1427;
      token_StartTag1.appendAttributeName('D');
      intArray1[1] = (-933);
      intArray1[2] = 0;
      intArray1[3] = 3243;
      token_StartTag0.finaliseTag();
      intArray1[4] = 13;
      // Undeclared exception!
      try { 
        token_StartTag1.appendAttributeValue(intArray1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.AbstractStringBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Token.CData token_CData0 = new Token.CData("");
      Token.CData token_CData1 = (Token.CData)token_CData0.data("");
      token_CData1.isComment();
      token_CData0.isEndTag();
      // Undeclared exception!
      try { 
        token_CData1.asEndTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$CData cannot be cast to org.jsoup.parser.Token$EndTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Token.CData token_CData0 = new Token.CData("|Pu");
      Token.CData token_CData1 = (Token.CData)token_CData0.data("|Pu");
      token_CData1.reset();
      token_CData1.isCData();
      token_CData0.toString();
      Token.TokenType.values();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.normalName();
      token_StartTag0.newAttribute();
      Token.StartTag token_StartTag1 = (Token.StartTag)token_StartTag0.name((String) null);
      token_CData0.toString();
      token_StartTag1.selfClosing = false;
      Token.StartTag token_StartTag2 = (Token.StartTag)token_StartTag1.reset();
      token_CData0.toString();
      Attributes attributes0 = new Attributes();
      token_StartTag0.attributes = attributes0;
      token_StartTag2.appendAttributeName('l');
      token_StartTag2.appendAttributeName('N');
      token_StartTag2.isDoctype();
      token_StartTag1.isCData();
      Token.StartTag token_StartTag3 = (Token.StartTag)token_StartTag0.reset();
      token_CData0.reset();
      token_StartTag3.name("");
      token_CData0.toString();
      // Undeclared exception!
      try { 
        token_StartTag0.toString();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be false
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      Token.EndTag token_EndTag1 = new Token.EndTag();
      token_EndTag1.getAttributes();
      token_EndTag1.reset();
      char char0 = 'Z';
      token_EndTag1.appendTagName('Z');
      // Undeclared exception!
      try { 
        token_EndTag0.asCharacter();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EndTag cannot be cast to org.jsoup.parser.Token$Character
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Token.TokenType.values();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = (Token.StartTag)token_StartTag0.reset();
      Token.StartTag token_StartTag2 = token_StartTag1.asStartTag();
      token_StartTag1.appendAttributeName("5}");
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("]]>", "]]>", attributes0);
      Attributes attributes1 = attributes0.put(attribute0);
      Attributes attributes2 = attributes1.clone();
      Attributes attributes3 = attributes2.put("]]>", true);
      attributes0.iterator();
      attributes1.put("]]>", "5}");
      Token.StartTag token_StartTag3 = token_StartTag2.nameAttr("5}", attributes3);
      token_StartTag3.toString();
      token_StartTag1.name();
      token_StartTag3.name("<5}  ]]>>");
      token_StartTag2.name();
      token_StartTag3.tokenType();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_StartTag1.isStartTag();
      token_StartTag3.normalName = "5}";
      token_StartTag2.appendAttributeValue("");
      // Undeclared exception!
      try { 
        token_StartTag1.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$StartTag cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Token.TokenType.values();
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = (Token.StartTag)token_StartTag0.reset();
      Token.StartTag token_StartTag2 = token_StartTag1.asStartTag();
      token_StartTag1.appendAttributeName("5}");
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("]]>", "]]>", attributes0);
      Attributes attributes1 = attributes0.put(attribute0);
      Attributes attributes2 = attributes1.clone();
      Attributes attributes3 = attributes2.put("]]>", true);
      attributes0.iterator();
      attributes1.put("]]>", "5}");
      attributes2.remove("5}");
      Token.StartTag token_StartTag3 = token_StartTag2.nameAttr("5}", attributes3);
      token_StartTag3.toString();
      token_StartTag1.name();
      token_StartTag3.name("<5}  ]]>>");
      token_StartTag2.name();
      token_StartTag3.tokenType();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_StartTag1.isStartTag();
      token_StartTag3.normalName = "5}";
      token_StartTag2.appendAttributeValue("");
      // Undeclared exception!
      try { 
        token_StartTag1.asDoctype();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$StartTag cannot be cast to org.jsoup.parser.Token$Doctype
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      token_StartTag0.normalName = "";
      Token.StartTag token_StartTag1 = new Token.StartTag();
      token_StartTag1.appendAttributeName("org.jsoup.parser.Token$EndTag");
      Token.TokenType token_TokenType0 = Token.TokenType.Doctype;
      token_StartTag1.type = token_TokenType0;
      token_StartTag1.newAttribute();
      token_StartTag0.newAttribute();
      token_StartTag0.isEOF();
      token_StartTag0.setEmptyAttributeValue();
      token_StartTag1.selfClosing = true;
      token_StartTag0.appendTagName("org.jsoup.parser.Token$EndTag");
      token_StartTag1.appendAttributeValue("");
      token_StartTag0.appendAttributeValue('u');
      token_StartTag0.finaliseTag();
      token_StartTag0.normalName();
      // Undeclared exception!
      try { 
        token_StartTag1.name();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be false
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Token.EOF token_EOF0 = new Token.EOF();
      Token.EOF token_EOF1 = (Token.EOF)token_EOF0.reset();
      token_EOF1.isDoctype();
      token_EOF0.tokenType();
      Token.TokenType token_TokenType0 = Token.TokenType.Character;
      token_EOF1.tokenType();
      token_EOF0.type = token_TokenType0;
      token_EOF0.isEOF();
      token_EOF1.isCharacter();
      Token.Comment token_Comment0 = new Token.Comment();
      // Undeclared exception!
      try { 
        token_EOF0.asStartTag();
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.jsoup.parser.Token$EOF cannot be cast to org.jsoup.parser.Token$StartTag
         //
         verifyException("org.jsoup.parser.Token", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Token.StartTag token_StartTag0 = new Token.StartTag();
      Token.StartTag token_StartTag1 = token_StartTag0.asStartTag();
      token_StartTag1.appendAttributeName('&');
      token_StartTag1.appendAttributeValue("g&|;nl2HLSC>a]|m;b>");
      char[] charArray0 = new char[0];
      token_StartTag1.appendAttributeValue(charArray0);
      token_StartTag1.nameAttr("g&|;nl2HLSC>a]|m;b>", (Attributes) null);
      token_StartTag1.toString();
      Token.TokenType token_TokenType0 = Token.TokenType.EOF;
      token_StartTag0.type = token_TokenType0;
      token_StartTag0.tokenType();
      token_StartTag0.asStartTag();
      Token.TokenType[] token_TokenTypeArray0 = Token.TokenType.values();
      assertEquals(6, token_TokenTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Token.EndTag token_EndTag0 = new Token.EndTag();
      token_EndTag0.tokenType();
      Token.TokenType token_TokenType0 = Token.TokenType.Comment;
      token_EndTag0.newAttribute();
      token_EndTag0.type = token_TokenType0;
      token_EndTag0.attributes = null;
      Token.EndTag token_EndTag1 = new Token.EndTag();
      token_EndTag1.isDoctype();
      token_EndTag1.getAttributes();
      Token.Doctype token_Doctype0 = new Token.Doctype();
      token_Doctype0.pubSysKey = "EndTag";
      token_Doctype0.getPublicIdentifier();
      Token.CData token_CData0 = new Token.CData("EndTag");
      Token.Doctype token_Doctype1 = (Token.Doctype)token_Doctype0.reset();
      token_Doctype1.getPublicIdentifier();
      token_Doctype1.getSystemIdentifier();
      token_EndTag1.isSelfClosing();
      token_CData0.toString();
      // Undeclared exception!
      try { 
        Token.TokenType.valueOf((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Name is null
         //
         verifyException("java.lang.Enum", e);
      }
  }
}
